# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Jahnavi Arora's Site
email: jahnaviarora@gmail.com
author: Jahnavi Arora
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta 
copyright: 'Copyright &copy; 2019 Jahnavi Arora. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/jahnavi-arora-18816b145/
  - title: github
    url: https://github.com/jahnaviarora
